### ISSUE TITLE
첫번째 학습 모델 디버깅 진행

### ISSUE THREAD

**Issue by eubinecto** [pirates14/BERT#10]
## Why?

<img width="645" alt="image" src="https://user-images.githubusercontent.com/56193069/143620229-0d69c9ff-6a13-4011-a28b-22fb8cab45f9.png">

학습이 분명 잘 된다고 생각했으나, 정작 예측을 해보니 학습에 사용된 문장임에도 불구하고 예측이 결과가 이상함.

## How?

아직까지는 저 문제를 어떻게 고쳐야할지 모르겠다. 우선 원인을 분석하는 것이 필요할 것.

원인을 분석해보면서, 리팩토링이 필요한 부분은 필요할 때마다 깔끔하게 정리해보자.

### Refactoring
- [x] 우선, 이슈와 동명의 브랜치 생성하기
- [x] requirements.txt  수정하기
- [x] MultiLabelNER -> BiLabelNER
- [x] val loader -> set shuffle to False
- [x] 학습 완료 후, 모델을 wandb에 올리도록 만들자! 이렇게 하면 굳이 로컬에 저장할 필요가 없음!

### 원인분석
- [ ] 일단 에러부터 reproduce해보고 시작하자!

**Comment by eubinecto** [comment]
## Requirements.txt 수정하기
### 왜?
M1 맥은  minicoda를 통해서 설치를 해야만 사이킷런이 설치가 되는데, 그러다보니 `pip freeze > requirements.txt` 를 했을 때 다음과 같은 d요상한 텍스트가 requirements.txt에 유입되었었다:

https://github.com/pirates14/BERT/blob/09b4d4b5a60afeec81e7ca919957c7042c7c8845/requirements.txt#L49-L50


그렇다보니 `pip3 -r install requirements.txt`를 하면 오류가 날수밖에.

### 어떻게?
음... 그렇다면 이렇게 설치된 모든 패키지를 다 나열하기보단,  필요한 라이브러리를 수동으로 나열하는게 더 적합할 것 같다:
```
transformers~=4.12.3
torchmetrics~=0.6.0
wandb~=0.12.6
pandas~=1.3.4
scikit-learn~=1.0.1
pytorch-lightning~=1.5.1
```

**Comment by eubinecto** [comment]
## 문제의 원인 가설 1: 문장의 주어가 상당부분 조사랑 같이 묶여서 토큰화가 되고 있기 때문은 아닐까?

<img width="645" alt="image" src="https://user-images.githubusercontent.com/56193069/143671418-32d5b723-aa91-4c80-be9a-720cec41cd89.png">


## 검증해보기
.. (실험)... 
기록.

## 분석 & 결론

가설이 맞다, 틀리다.


## 해결책

**Comment by hale-in** [comment]
**### 문제의 원인 가설 2: infer에서 cls토큰을 제외하고 문장만 입력값으로 넣었기 때문아닐까? (은정님@eeunn )**

### **검증해보기**
